# Validate UK Postcodes Project

### Current Implementation
- Uses API to validate inputted postcode (returns valid or not valid)
- If valid, adds extra address information to dataset

### Desired Implementation
- For every postcode that's valid, use regex to pick out the number in the address line and autocomplete the address
- Add the first line of address from an API for a data cleanse, not currently availble from API in project
- Connect to a database for source data

In [1]:
import urllib.request as req
import json
import pandas as pd

In [7]:
df = pd.read_csv(r"C:\Source\Addresses.csv")
df.head(6)

   Id              line1  postcode
0   1       11 High Fold  BD20 5TH
1   2    5 Bescaby Grove  BD17 6ST
2   3  7 Westfield Drive  BD20 5BJ
3   4    3 Gibbons Drive   S14 1BQ
4   5     5 Baildon Road   S43 SSS
5   6         Berry Lane    E1 7BS

In [3]:
def loadJsonResponse(url):
    return json.loads(req.urlopen(url).read())#['result']

def validatePostcode(postcode):
    url = 'https://api.postcodes.io/postcodes/{}/validate'.format(postcode)
    return loadJsonResponse(url)

def randomPostcode():
    url = 'https://api.postcodes.io/random/postcodes'
    return loadJsonResponse(url)

def queryPostcode(postcode):
    url = 'https://api.postcodes.io/postcodes?q={}'.format(postcode)
    return loadJsonResponse(url)

def getAutoCompletePostcode(postcode):
    url = 'https://api.postcodes.io/postcodes/{}/autocomplete'.format(postcode)
    return loadJsonResponse(url)

In [4]:
for index, row in df.iterrows():
    
    results = queryPostcode(row['postcode'].replace(" ", ""))
    
    # If the json body returns None, only iterate through results that are complete
    if results['result'] is not None:
       
    # Access object 1 level below the json body
        result = results['result'][0]
    
    # Assign the results to a new column in the existing rows
       
        df.loc[index, "City"] = result['admin_district']
        df.loc[index, "Region"] = result['region']
        df.loc[index, "Country"] = result['country'].replace("England", "United Kingdom")
        df.loc[index, "Control"] = "Valid"
    
    # For all results that aren't valid, return "Not Valid"
    else:
        df.loc[index, "Control"] = "Not Valid"

df.head(6)

,Id,line1,postcode,TownCity,Region,Country,Control
0,1,11 High Fold,BD20 5TH,Bradford,Yorkshire and The Humber,United Kingdom,Valid
1,2,5 Bescaby Grove,BD17 6ST,Bradford,Yorkshire and The Humber,United Kingdom,Valid
2,3,7 Westfield Drive,BD20 5BJ,Bradford,Yorkshire and The Humber,United Kingdom,Valid
3,4,3 Gibbons Drive,S14 1BQ,Sheffield,Yorkshire and The Humber,United Kingdom,Valid
4,5,5 Baildon Road,S43 SSS,NaN,NaN,NaN,Not Valid
5,6,Berry Lane,E1 7BS,City of London,London,United Kingdom,Valid

In [5]:
df.loc[df['Control'] == "Not Valid"]

   Id           line1 postcode TownCity Region Country    Control
4   5  5 Baildon Road  S43 SSS      NaN    NaN     NaN  Not Valid

In [ ]:
# Iterate through dataframe rows
#for index, row in df.iterrows():

# data = []

# for postcode in df['postcode']:
    
#     results = queryPostcode(postcode.replace(" ", ""))     
#     data.append(results)

# print(data)




# # Iterate through dataframe rows
# for index, row in df.iterrows():
    
#     if queryPostcode(row['postcode'].replace(" ", ""))['status'] == 200:
        
#         # Send the values from postcode column to queryPostcode function and get results
#         result = queryPostcode(row['postcode'].replace(" ", ""))['result'][0]
#         #print(result)
#         # Assign the results to a new column in the existing rows
#         df.loc[index, "TownCity"] = result['parliamentary_constituency']
#         df.loc[index, "Region"] = result['pfa']
#         df.loc[index, "Country"] = result['country'].replace("England", "United Kingdom")
#         df.loc[index, "Control"] = "Valid"
    
#     else:
#         df.loc[index, "Control"] = "Not Valid"

# df.head()

In [ ]:
# #for column in df.columns[2:]:
#     #myList = df[column].values
#    # myList = list(map(str.strip, myList))

# # For every postcode in postcodes column, hit the queryPostcode API call and return specific address data
# for postcode in postcodes:
#     result = queryPostcode(postcode)['result'][0]
    
#     postcodeList = result['postcode']
    
# #     addressDict = {
# #                'TownCity': result['parliamentary_constituency'],
# #                'Region': result['pfa'],
# #                'Postcode1': result['postcode'],
# #                'Country': result['country']
        
# #               }
    
#     df['Postcode1'] = postcodeList
#     #print(result['postcode'])

# print(df)
    
    
    
    
    
    
#     #df['Postcode1'] = postcode1
    
#     #addressList = [result['parliamentary_constituency'], result['pfa'], result['postcode'], result['country']]

    
# #     df['Region'] = result['pfa']
# #     df['TownCity'] = result['parliamentary_constituency']
# #     df['Postcode1'] = result['postcode']
    
    
#     #df2 = pd.append([df['Id'], 'TownCity'] = addressDict['TownCity'])
    
#     #df2 = df.insert('TownCity', addressDict['TownCity'])
    
#     #townList = [result['parliamentary_constituency']]
#     #df['TownCity'] = townList
    
    
    
#     #df2 = df.append(addressDict, ignore_index=True)
#     #df['TownCity'] = addressDict['TownCity']
#     #df['Region'] = addressDict['Region']
#     #df['Country'] = addressDict['Country']
# #print(df)
#     #print(addressDict)
#     #df['TownCity']
    
    
#  #   print(result['parliamentary_constituency'])
#   #  print(result['pfa'])
#    # print(result['postcode'])
#     #print(result['country'])